---
title: "ME115 - Linguagem R"
subtitle: "Projeto Final"
author: "Profa. Samara Kiihl"
output: html_document
---

# Projeto Final

#### Introdução

Nesse projeto vocês irão aplicar todo conhecimento adquirido ao longo do semestre. 
O projeto será executado em grupos de no máximo dois alunos. Cada grupo deverá selecionar um conjunto de dados de seu interesse para trabalhar. Uma dica é utilizar conjuntos de dados disponíveis na plataforma Kaggle  ([https://www.kaggle.com/datasets](https://www.kaggle.com/datasets)). Para alunos que dependerão totalmente apenas do RStudio Cloud, considerem com cuidado os limites de memória da plataforma.

Baseando-se nos dados selecionados, cada grupo irá elaborar uma pergunta de interesse que deverá ser respondida utilizando métodos estatísticos. Será obrigatório que o projeto contemple os principais tópicos vistos durante o curso, descritos a seguir, com respectivos pacotes:

- Importação do banco de dados: diretamente da web (recomendado) ou baixando o arquivo csv/txt (`readr`)

- Limpeza e Manipulação dos dados (`tidyr` e `dplyr`)

- Visualização (`ggplot2`)

- Análise Exploratória e/ou Descritiva


#### Relatório

O relatório deverá ser feito de maneira **reprodutível** utilizando o R Markdown, que deverá gerar um arquivo `.pdf` com no máximo **8 páginas**. Códigos, mensagens e avisos do R não devem estar visíveis no `.pdf` do relatório. Vocês irão entregar os arquivos `.Rmd`, o `.pdf` resultante, bem como arquivos auxiliares necessários para a execução do `.Rmd`. A forma de envio será especificada mais adiante. O envio deverá ser feito no dia **23 de junho**. Não serão aceitas submissões fora do prazo.


Cada grupo deverá apresentar no relatório:

- **Título**

- **Introdução**: apresentação do problema/pergunta de interesse.

- **Banco de Dados**: descrição detalhadada das variáveis, incluindo o *link* para obtenção dos dados. 

- **Análise Exploratória e/ou Descritiva**: principais estatísticas sumárias e gráficos relevantes para responder a pergunta de interesse.

- **Considerações finais**

- **Bibliografia** (opcionalmente, se necessário)

Para auxiliar na escrita do relatório, recomendamos os livros:

* Peng, R. D. (2016) [Report Writing for Data Science in R](https://leanpub.com/reportwriting).
* Leek, J. (2015) [The Elements of Data Analytic Style](https://leanpub.com/datastyle).



#### Apresentação

Cada grupo deverá preparar uma apresentação que será submetida via Google Classroom. O grupo deverá enviar o **arquivo dos slides** e o **arquivo do vídeo da apresentação**. A duração da apresentação é de no máximo 5 minutos. O arquivo deverá ser submetido até o dia **25 de junho**.

Algumas ferramentas para gravar vídeos com apresentação de slides:

* [Google Meet](https://drive.google.com/file/d/1L8zqWGjlsPzodWFkO-ZTVLp4QP5pIIn8/view)
* [Power Point](https://drive.google.com/file/d/1CcURCCdDrAfWwoKye9vRuwgNFK5yPoWk/view)
* [QuickTime](https://prezi.com/j8onzfdcywnl/criando-videos-com-o-quicktime/?utm_campaign=share&utm_medium=copy)

É importante que o grupo teste a ferramenta com antecedência.

